[bootstrap.user]
login_shell = "/bin/fish"

[bootstrap.packages]
"dnf:fish" = "latest"
"dnf:glibc-langpack-en" = "latest"
"dnf:emacs-gtk+x11" = "latest"
"dnf:enchant2-devel" = "latest"
"dnf:atuin" = "latest"
"dnf:bat" = "latest"
"dnf:fd-find" = "latest"
"dnf:fzf" = "latest"
"dnf:mise" = "latest"
"dnf:ripgrep" = "latest"
"dnf:wget2-wget" = "latest"
"dnf:zip" = "latest"
"dnf:python3" = "latest"
"dnf:black" = "latest"
"dnf:python3-isort" = "latest"
"dnf:python3-jinja2-cli" = "latest"
"dnf:python3-lsp-server" = "latest"
"dnf:python3-lsp-ruff" = "latest"
"dnf:ruff" = "latest"
"dnf:btop" = "latest"
"dnf:htop" = "latest"
"dnf:ncdu" = "latest"
"dnf:jq" = "latest"
"dnf:yq" = "latest"
"dnf:mtr" = "latest"
"dnf:bind-utils" = "latest"
"dnf:kind" = "latest"
"dnf:openssl" = "latest"
"dnf:postgresql" = "latest"
