[settings]
experimental = true

[bootstrap.repos]
"~/org" = { url = "git@github.com:kneilb/org.git" }
"~/repos/mk/io/mkio-devenv" = { url = "git@github-mk:mediakind-labs/mkio-devenv.git" }
"~/repos/mk/io/mkio-api" = { url = "git@github-mk:mediakind-labs/mkio-api.git" }
"~/repos/mk/io/mkio-ui" = { url = "git@github-mk:mediakind-labs/mkio-ui.git" }
"~/repos/mk/io/mkio-eae" = { url = "git@github-mk:mediakind-labs/mkio-eae.git" }
"~/repos/mk/io/mkio-cloud-infrastructure" = { url = "git@github-mk:mediakind-labs/mkio-cloud-infrastructure.git" }
"~/repos/mk/io/mkio-provisioner" = { url = "git@github-mk:mediakind-labs/mkio-provisioner.git" }
"~/repos/mk/io/mkio-coin" = { url = "git@github-mk:mediakind-labs/mkio-coin.git" }
"~/repos/mk/io/mkio-remote-access" = { url = "git@github-mk:mediakind-labs/mkio-remote-access.git" }
"~/repos/mk/io/mkio-support" = { url = "git@github-mk:mediakind-labs/mkio-support.git" }
"~/repos/mk/io/mk-operator" = { url = "git@github-mk:mediakind-labs/mk-operator.git" }
"~/repos/mk/io/mk-orchestrator" = { url = "git@github-mk:mediakind-labs/mk-orchestrator.git" }

[tools]
aws = "latest"
azure-cli = "latest"
gcloud = "latest"
gh = "latest"
"go:golang.org/x/tools/gopls" = "latest"
golang = "latest"
helm = "latest"
jless = "latest"
k9s = "latest"
kubectl = "latest"
rust = "latest"
rust-analyzer = "latest"
terraform = "1.9.6"
uv = "latest"
opencode = "latest"
node = "latest"
"npm:typescript-language-server" = "latest"
