[bootstrap.user]
login_shell = "/opt/homebrew/bin/fish"

[bootstrap.packages]
"brew:fish" = "latest"
"brew:bash" = "latest"
"brew:enchant" = "latest"
"brew:atuin" = "latest"
"brew:bat" = "latest"
"brew:chezmoi" = "latest"
"brew:fd" = "latest"
"brew:fzf" = "latest"
"brew:mise" = "latest"
"brew:ripgrep" = "latest"
"brew:wget" = "latest"
"brew:zip" = "latest"
"brew:pkgconf" = "latest"
"brew:python-lsp-server" = "latest"
"brew:ruff" = "latest"
"brew:btop" = "latest"
"brew:htop" = "latest"
"brew:ncdu" = "latest"
"brew:jq" = "latest"
"brew:yq" = "latest"
"brew:mtr" = "latest"

"brew:rust-analyzer" = "latest"
"brew:rustup" = "latest"
"brew:starship" = "latest"
